# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/aad_domainservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/apimanagement_service/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cache_redis/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cdn_cdnwebapplicationfirewallpolicies/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cdn_profiles' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cognitiveservices_accounts/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_cloudservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_cloudservices_roles/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_disks/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachines/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachinescalesets/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachinescalesets_virtualmachines/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerinstance_containergroups/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerinstance_containerscalesets/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerregistry_registries/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerservice_managedclusters/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dataprotection_backupvaults/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformariadb_servers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformysql_flexibleservers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformysql_servers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_flexibleservers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_servergroupsv2/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_servers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_serversv2/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_cassandraclusters/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_databaseaccounts/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_mongocluster/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_domains/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_eventsubscriptions/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_extensiontopics/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_namespaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_partnernamespaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_partnertopics/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_systemtopics/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_topics/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventhub_clusters/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventhub_namespaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/keyvault_managedhsms/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/keyvault_vaults/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/kubernetes_connectedclusters/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/kubernetesconfiguration_extensions/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces_onlineendpoints/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces_onlineendpoints_deployments/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_applicationgateways/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_azurefirewalls/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_loadbalancers/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_natgateways/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_networkinterfaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/servicebus_namespaces/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_managedinstances/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_servers_databases/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_servers_elasticpools/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_blobservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_fileservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_objectreplicationpolicies/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_queueservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_storagetasks/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_tableservices/dashboards/overview' # Location of package manifests
    schedule:
      interval: 'daily'