# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/aad_domainservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/apimanagement_service' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cache_redis' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cdn_cdnwebapplicationfirewallpolicies' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cdn_profiles' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/cognitiveservices_accounts' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_cloudservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_cloudservices_roles' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_disks' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachines' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachinescalesets' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/compute_virtualmachinescalesets_virtualmachines' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerinstance_containergroups' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerinstance_containerscalesets' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerregistry_registries' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/containerservice_managedclusters' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dataprotection_backupvaults' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformariadb_servers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformysql_flexibleservers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbformysql_servers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_flexibleservers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_servergroupsv2' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_servers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/dbforpostgresql_serversv2' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_cassandraclusters' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_databaseaccounts' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/documentdb_mongocluster' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_domains' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_eventsubscriptions' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_extensiontopics' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_namespaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_partnernamespaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_partnertopics' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_systemtopics' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventgrid_topics' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventhub_clusters' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/eventhub_namespaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/keyvault_managedhsms' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/keyvault_vaults' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/kubernetes_connectedclusters' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/kubernetesconfiguration_extensions' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces_onlineendpoints' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/machinelearningservices_workspaces_onlineendpoints_deployments' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_applicationgateways' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_azurefirewalls' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_loadbalancers' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_natgateways' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/network_networkinterfaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/servicebus_namespaces' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_managedinstances' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_servers_databases' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/sql_servers_elasticpools' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_blobservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_fileservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_objectreplicationpolicies' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_queueservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_storagetasks' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/storage_storageaccounts_tableservices' # Location of package manifests
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform' # See documentation for possible values
    directory: '/azure/tester' # Location of package manifests
    schedule:
      interval: 'daily'